apiVersion: v1
kind: Secret
metadata:
  name: jpx-db-secret
  labels:
    # 이 Secret은 자바와 파이썬 모두에서 참조하므로 
    # 특정 앱에 종속되지 않는 라벨로 변경하거나 그대로 두어도 상관없습니다.
    app: jpx-sentinel 
type: Opaque
data:
  # values.yaml에 있는 평문(plain text)을 Base64로 인코딩하여 주입
  username: {{ .Values.global.db.username | b64enc }}
  password: {{ .Values.global.db.password | b64enc }}
  slack_webhook_url: {{ .Values.global.slack_webhook_url | b64enc }}
  
  # 추가된 DB 접속 정보
  db-host: {{ .Values.global.db.host | b64enc }}
  db-name: {{ .Values.global.db.name | b64enc }}